dist: xenial
language: csharp
env:
 - CONFIGURATION=Release
services:
  - redis-server
  - docker
mono: none
dotnet: 2.2.100
script:
 - set -e
 - docker pull microsoft/mssql-server-linux:2017-latest
 - docker run -p 1433:1433 -e 'SA_PASSWORD=Password12!' -e 'ACCEPT_EULA=Y' -d microsoft/mssql-server-linux:2017-latest
 - sleep 180
 - cd build
 - export PATH="$PATH:/home/travis/.dotnet/tools"
 - ./build.sh