language: csharp
services:
  - redis-server
  - docker
mono: none
dotnet: 1.0.4
dist: trusty
script:
 - set -e
 - docker pull microsoft/mssql-server-linux
 - docker run -p 1433:1433 -e 'SA_PASSWORD=Password12!' -e 'ACCEPT_EULA=Y' -d microsoft/mssql-server-linux
 - dotnet restore "test\TipsAndTricksLibrary.Tests" --no-dependencies
 - dotnet restore "test\TechnologyUsageTests" --no-dependencies
 - dotnet build "src\TipsAndTricksLibrary" -c Release --no-dependencies
 - dotnet build "test\TipsAndTricksLibrary.Tests" -c Release --no-dependencies
 - dotnet build "test\TechnologyUsageTests" -c Release --no-dependencies
 - dotnet test "test\TipsAndTricksLibrary.Tests\TipsAndTricksLibrary.Tests.csproj" -c Release --no-build