version: 1.0.{build}
configuration: Release
platform: Any CPU
environment:
  Appveyor: true
services: mssql2014
before_build:
- cmd: >-
    dotnet restore "src\TipsAndTricksLibrary"

    dotnet restore "test\TechnologyUsageTests"

    dotnet restore "test\TipsAndTricksLibrary.Tests"
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: dotnet test "test\TipsAndTricksLibrary.Tests" -c %CONFIGURATION%
deploy: off