version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu
configuration: Release
test: off
deploy: off
skip_commits:
  files:
  - LICENSE
  - README.md
  - .travis.yml
  - TipsAndTricksLibrary.sln.DotSettings
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
    services: mssql2016
    build_script:
      - ps: >-
          nuget install redis-64 -excludeversion

          redis-64\tools\redis-server.exe --service-install

          redis-64\tools\redis-server.exe --service-start
    
          cd build

          .\build.ps1
        
  -
    matrix:
      only:
        - image: ubuntu1804
    services: 
      - mssql
      - redis
    build_script:
      - sh: >-
          cd build

          ./build.sh