name: ci workflow

on:
  - push
  - pull_request

jobs:
  test:
    name: test
    
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Password12!

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          script-path: ./build/build.cake
          target: Test
          verbosity: Verbose
          arguments: |
            configuration: Release
            nuget_useinprocessclient: true

